/**
 * src/blog/postMeta.js
 * Post metadata with no JSX imports, so it can be read by things that cannot
 * run a bundler. api/sitemap.js is the reason this file exists: the sitemap
 * has to know which posts are live, and a Vercel function cannot import the
 * .jsx article bodies that posts.js pulls in.
 *
 * This is the single source of truth for slug, date, title and description.
 * posts.js attaches the article components on top of it.
 */

// Posts go live at 9am Mountain, anchored to a fixed offset rather than the
// reader's clock. Two reasons it has to be absolute: a visitor in Sydney was
// seeing scheduled posts most of a day before Boyd did, and the sitemap runs
// on a UTC server that has to agree with the browser about what is published.
// If they disagree, the sitemap advertises a URL that still serves noindex,
// which is the Search Console warning this file was written to end.
// -07:00 is MST. In summer it lands at 10am MDT, which nobody will notice.
const PUBLISH_HOUR = "T09:00:00-07:00";

export function publishedAt(post) {
  return new Date(post.date + PUBLISH_HOUR);
}

export function isPublished(post, now = new Date()) {
  return publishedAt(post) <= now;
}

export const postMeta = [
  // ── Live now ──
  {
    slug: "how-much-does-a-website-cost-boise-idaho",
    title: "How Much Does a Website Cost in Boise, Idaho? (2026 Guide)",
    description: "An honest breakdown of website costs in the Boise market, from DIY Wix to custom agencies. What drives the price, what red flags to watch for, and what you actually get at each tier.",
    date: "2026-06-11",
    dateDisplay: "June 11, 2026",
    readTime: "7 min read",
    category: "Web Design",
    coverImage: "/blog/web-design-cost.webp",
    coverAlt: "Web design pricing breakdown for Boise, Idaho businesses",
  },
  {
    slug: "ai-chatbot-vs-answering-service-boise-contractors",
    title: "AI Chatbot vs. Answering Service: What Boise Contractors Actually Need",
    description: "Both promise to capture leads after hours. Here's a straight comparison of cost, capability, and fit for Treasure Valley service businesses, including a head-to-head feature table.",
    date: "2026-06-11",
    dateDisplay: "June 11, 2026",
    readTime: "6 min read",
    category: "AI Tools",
    coverImage: "/blog/ai-chatbot-answering.webp",
    coverAlt: "AI chatbot versus live answering service comparison for contractors",
  },
  {
    slug: "boise-hvac-companies-24-7-lead-capture",
    title: "Why Boise HVAC Companies Are Losing Leads After 5pm",
    description: "HVAC calls spike exactly when offices close, summer heat waves and winter breakdowns don't wait for business hours. Here's what's being lost and how to stop it.",
    date: "2026-06-11",
    dateDisplay: "June 11, 2026",
    readTime: "5 min read",
    category: "Lead Generation",
    coverImage: "/blog/hvac-leads.webp",
    coverAlt: "HVAC technician responding to an after-hours call in Boise",
  },
  {
    slug: "from-wix-to-custom-boise-window-cleaning",
    title: "From Wix to Custom: What a Boise Window Cleaning Company Gained by Rebuilding Their Site",
    description: "When Sudz Window & Gutter outgrew their Wix site, we rebuilt it on a custom React stack with an AI receptionist. Here's what changed, and what it means for other Boise service businesses still on DIY platforms.",
    date: "2026-06-11",
    dateDisplay: "June 11, 2026",
    readTime: "5 min read",
    category: "Case Study",
    coverImage: "/blog/wix-to-custom.webp",
    coverAlt: "Before and after comparison of Sudz Window Cleaning website redesign",
  },

  // ── Scheduled — one per Monday ──
  {
    slug: "boise-plumbing-website-mobile",
    title: "Does Your Boise Plumbing Website Work on a Phone? Here's How to Check",
    description: "More than half of local service searches happen on a phone. If your plumbing site is slow, hard to tap, or unreadable without zooming, you're losing calls every day. Here's how to find out.",
    date: "2026-06-22",
    dateDisplay: "June 22, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/boise-plumbing-mobile.webp",
    coverAlt: "Plumber's wrench and tools for sink repair representing Boise plumbing services",
  },
  {
    slug: "google-business-profile-treasure-valley-contractors",
    title: "How Google Business Profile Works for Treasure Valley Contractors",
    description: "The local map pack drives a large share of service business calls. Here's what Google Business Profile actually does, why it matters, and how to set it up correctly.",
    date: "2026-06-29",
    dateDisplay: "June 29, 2026",
    readTime: "5 min read",
    category: "Lead Generation",
    coverImage: "/blog/google-business-profile.webp",
    coverAlt: "Google Maps location pin on paper representing a local business profile",
  },
  {
    slug: "local-seo-boise-service-businesses",
    title: "Local SEO for Service Businesses: What Actually Moves the Needle in Boise",
    description: "Local SEO for service businesses is different from general SEO. Here's what Google actually uses to rank local contractors, and what you can do today to improve your position.",
    date: "2026-07-06",
    dateDisplay: "July 6, 2026",
    readTime: "5 min read",
    category: "Web Design",
    coverImage: "/blog/local-seo-boise.webp",
    coverAlt: "SEO audit blocks representing local search optimization for Boise service businesses",
  },
  {
    slug: "landscaping-nampa-google",
    title: "Why Landscaping Companies in Nampa Are Invisible on Google",
    description: "Landscaping searches in Nampa are high-intent and underserved. Here's why most local landscaping companies don't rank, and the specific fixes that change that.",
    date: "2026-07-13",
    dateDisplay: "July 13, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/landscaping-nampa.webp",
    coverAlt: "Lawn care worker cutting grass representing landscaping services in Nampa Idaho",
  },
  {
    slug: "boise-roofing-website-mistakes",
    title: "5 Things Boise Roofing Websites Get Wrong",
    description: "Roofing is one of the most competitive local search categories in Boise. These five mistakes are costing roofing companies leads every week, and all of them are fixable.",
    date: "2026-07-20",
    dateDisplay: "July 20, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/boise-roofing.webp",
    coverAlt: "Professional roofer installing shingles on a house in Boise Idaho",
  },
  {
    slug: "after-hours-lead-capture-service-businesses",
    title: "What Happens When a Customer Finds Your Site at 11pm",
    description: "Most local service searches happen outside business hours. The company that captures that inquiry first wins the job. Here's what that looks like in practice.",
    date: "2026-07-27",
    dateDisplay: "July 27, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/after-hours-leads.webp",
    coverAlt: "People using smartphones in the dark representing after-hours customer inquiries",
  },
  {
    slug: "google-reviews-treasure-valley-businesses",
    title: "How to Get More Google Reviews for Your Treasure Valley Business",
    description: "Reviews are a direct local search ranking signal and one of the biggest trust factors for new customers. Here's a practical system for building review volume consistently.",
    date: "2026-08-03",
    dateDisplay: "August 3, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/google-reviews.webp",
    coverAlt: "Five yellow stars representing Google review ratings for Treasure Valley businesses",
  },
  {
    slug: "service-area-pages-local-seo-boise",
    title: "What Makes a Service Area Page Actually Rank on Google",
    description: "If you serve multiple cities in the Treasure Valley, a single service area list won't rank. Here's what dedicated location pages need to do to show up in city-specific searches.",
    date: "2026-08-10",
    dateDisplay: "August 10, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/service-area-pages.webp",
    coverAlt: "Aerial view of suburban neighborhood representing Treasure Valley service areas",
  },
  {
    slug: "pressure-washing-website-boise",
    title: "Pressure Washing Business Website Mistakes Boise Owners Make",
    description: "Pressure washing is visual, seasonal, and highly local. Here's what most Boise pressure washing sites are missing and how to fix it to capture more warm-weather leads.",
    date: "2026-08-17",
    dateDisplay: "August 17, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/pressure-washing-boise.webp",
    coverAlt: "Person pressure washing house siding representing cleaning services in Boise",
  },
  {
    slug: "pest-control-lead-capture-treasure-valley",
    title: "Why Pest Control Companies Lose Leads After Hours",
    description: "Pest problems don't happen on a schedule. If your pest control website can't capture inquiries at 9pm on a Saturday, you're losing those jobs to competitors who can.",
    date: "2026-08-24",
    dateDisplay: "August 24, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/pest-control.webp",
    coverAlt: "Pest control technician performing professional fumigation treatment",
  },
  {
    slug: "google-analytics-search-console-boise",
    title: "Google Analytics vs. Search Console: What Each One Tells Your Boise Business",
    description: "These two free tools show completely different things about your website's performance. Here's what each one does and how to use them together to improve your results.",
    date: "2026-08-31",
    dateDisplay: "August 31, 2026",
    readTime: "5 min read",
    category: "Web Design",
    coverImage: "/blog/google-analytics.webp",
    coverAlt: "Analytics graphs on laptop screen showing website performance data",
  },
  {
    slug: "tree-service-website-treasure-valley",
    title: "Is Your Treasure Valley Tree Service Website Helping or Hurting?",
    description: "Tree service is high-trust and high-ticket. Here's what a tree service website needs to show to build that trust quickly and capture emergency and planned service leads.",
    date: "2026-09-07",
    dateDisplay: "September 7, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/tree-service.webp",
    coverAlt: "Arborist in safety gear working on a tree representing tree services in Treasure Valley",
  },
  {
    slug: "mobile-first-website-nampa-service-business",
    title: "What a Mobile-First Website Actually Means for a Nampa Service Business",
    description: "Mobile-first isn't just a design trend, it's how Google indexes and ranks your site. Here's what it means technically and what it looks like for a local service business.",
    date: "2026-09-14",
    dateDisplay: "September 14, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/mobile-first-nampa.webp",
    coverAlt: "Laptops and tablet on a desk representing mobile-first web design for Nampa businesses",
  },
  {
    slug: "eagle-idaho-local-search-ranking",
    title: "How Eagle, Idaho Businesses Can Rank Higher in Local Search",
    description: "Eagle is one of the fastest-growing cities in Idaho and an underserved local search market. Here's a focused approach to ranking for Eagle-specific service searches.",
    date: "2026-09-21",
    dateDisplay: "September 21, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/eagle-idaho.webp",
    coverAlt: "Green field with mountain peak backdrop representing Eagle Idaho landscape",
  },
  {
    slug: "electricians-boise-need-real-website",
    title: "Why Electricians in Boise Need More Than a Facebook Page",
    description: "Facebook doesn't rank in Google search. If your electrical business runs primarily on a Facebook page, here's what you're missing and what a real website would change.",
    date: "2026-09-28",
    dateDisplay: "September 28, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/electricians-boise.webp",
    coverAlt: "Electrician testing an open electrical panel with a multimeter in Boise",
  },
  {
    slug: "garage-door-boise-website-leads",
    title: "How Garage Door Companies Lose Jobs to Competitors With Better Websites",
    description: "Garage door calls are often urgent and decided in seconds. Here's what separates the Boise garage door companies that win those calls from the ones that don't.",
    date: "2026-10-05",
    dateDisplay: "October 5, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/garage-door-boise.webp",
    coverAlt: "Modern suburban house with driveway representing garage door services in Boise",
  },
  {
    slug: "website-hosting-explained-boise-businesses",
    title: "What Is Website Hosting and Why It Matters for Your Boise Business",
    description: "Cheap hosting quietly hurts your search rankings and drives visitors away. Here's a plain-language explanation of what hosting does and what to look for.",
    date: "2026-10-12",
    dateDisplay: "October 12, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/website-hosting.webp",
    coverAlt: "Server racks in a data center representing website hosting infrastructure",
  },
  {
    slug: "respond-to-negative-google-reviews",
    title: "How to Respond to Negative Google Reviews Without Making It Worse",
    description: "Every service business gets a bad review eventually. How you respond to it matters more than most owners realize. Here's a straightforward approach that builds trust.",
    date: "2026-10-19",
    dateDisplay: "October 19, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/respond-reviews.webp",
    coverAlt: "Business owner at desk with laptop representing responding to Google reviews",
  },
  {
    slug: "stone-masonry-website-boise",
    title: "Stone and Masonry Businesses in Boise: What Your Website Should Show",
    description: "Masonry work sells itself visually. Here's what a stone and masonry website needs to show potential customers, and how to structure it to rank for the searches that matter.",
    date: "2026-10-26",
    dateDisplay: "October 26, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/stone-masonry-boise.webp",
    coverAlt: "Rustic stone wall with garden pots representing masonry work in Boise",
  },
  {
    slug: "carpet-cleaning-meridian-lead-capture",
    title: "Why Carpet Cleaning Companies in Meridian Need 24/7 Lead Capture",
    description: "Carpet cleaning decisions often happen in the evening after a mess or before guests arrive. Here's how Meridian carpet cleaning companies can capture those after-hours inquiries.",
    date: "2026-11-02",
    dateDisplay: "November 2, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/carpet-cleaning-meridian.webp",
    coverAlt: "Professional using a vacuum cleaner for carpet cleaning in a Meridian home",
  },
  {
    slug: "caldwell-idaho-local-seo",
    title: "What Caldwell, Idaho Businesses Should Know About Local Search",
    description: "Caldwell is growing fast and underserved in local search. Service businesses willing to target it specifically can rank well with focused effort most competitors aren't making.",
    date: "2026-11-09",
    dateDisplay: "November 9, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/caldwell-idaho.webp",
    coverAlt: "Aerial view of residential neighborhood representing Caldwell Idaho",
  },
  {
    slug: "google-ads-vs-seo-boise-contractors",
    title: "Google Ads vs. SEO: A Straight Answer for Boise Contractors",
    description: "Should you run Google Ads or focus on SEO? The honest answer depends on where your business is and what you need. Here's a clear breakdown without the agency spin.",
    date: "2026-11-16",
    dateDisplay: "November 16, 2026",
    readTime: "5 min read",
    category: "Web Design",
    coverImage: "/blog/google-ads-vs-seo.webp",
    coverAlt: "Marketing team collaborating representing Google Ads and SEO strategy for Boise contractors",
  },
  {
    slug: "window-cleaning-boise-found-on-google",
    title: "How Window Cleaning Companies in Boise Get Found on Google",
    description: "Window cleaning is recurring, relationship-based, and highly local. Here's what it takes to show up when Boise homeowners search for it, including seasonal timing that most sites miss.",
    date: "2026-11-23",
    dateDisplay: "November 23, 2026",
    readTime: "4 min read",
    category: "Lead Generation",
    coverImage: "/blog/window-cleaning-boise.webp",
    coverAlt: "Hand on glass window representing professional window cleaning services in Boise",
  },
  {
    slug: "homepage-converts-visitors-to-calls",
    title: "What Makes a Homepage Actually Convert Visitors Into Calls",
    description: "A homepage that looks good and a homepage that generates calls are not the same thing. Here's what the difference comes down to for service businesses in the Treasure Valley.",
    date: "2026-11-30",
    dateDisplay: "November 30, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/homepage-conversion.webp",
    coverAlt: "Businessman at desk with laptop representing website conversion optimization",
  },
  {
    slug: "is-your-website-bringing-in-leads",
    title: "How to Know If Your Website Is Actually Bringing In Leads",
    description: "Most service business owners don't have clear data on whether their site is generating leads. Here's how to find out using free tools, and what to do with what you find.",
    date: "2026-12-07",
    dateDisplay: "December 7, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/website-leads.webp",
    coverAlt: "Marketing professional with phone and laptop reviewing website lead analytics",
  },
  {
    slug: "handyman-business-website-treasure-valley",
    title: "Why Handyman Businesses in the Treasure Valley Need a Real Website",
    description: "Most handyman operators rely on referrals alone. Here's why building a simple web presence opens a consistent inbound lead channel that referrals can't match.",
    date: "2026-12-14",
    dateDisplay: "December 14, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/handyman-treasure-valley.webp",
    coverAlt: "Worker with tool belt and safety helmet representing handyman services in Treasure Valley",
  },
  {
    slug: "service-pages-seo-boise",
    title: "What to Put on Your Service Pages to Rank in Boise",
    description: "Service pages are what actually rank for the searches that produce calls. Here's what each service page needs to do its job in local search.",
    date: "2026-12-21",
    dateDisplay: "December 21, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/service-pages-seo.webp",
    coverAlt: "Laptop displaying graphs representing SEO-optimized service pages for Boise businesses",
  },
  {
    slug: "painting-contractors-boise-online",
    title: "How Painting Contractors in Boise Can Stand Out Online",
    description: "Painting is competitive in the Treasure Valley. Here's how to use your website to build the visual proof and local visibility that brings in more bids.",
    date: "2026-12-28",
    dateDisplay: "December 28, 2026",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/painting-contractors-boise.webp",
    coverAlt: "Painting contractor using a roller to paint a wall in a Boise home",
  },
  {
    slug: "ai-receptionist-vs-contact-form",
    title: "AI Receptionist vs. Contact Form: What Actually Captures More Leads",
    description: "Both sit on your website and collect customer information, but they produce very different results. Here's a direct comparison for Treasure Valley service businesses.",
    date: "2027-01-05",
    dateDisplay: "January 5, 2027",
    readTime: "5 min read",
    category: "AI Tools",
    coverImage: "/blog/ai-receptionist.webp",
    coverAlt: "AI neural network illustration representing AI receptionist technology for service businesses",
  },
  {
    slug: "website-that-gets-calls-boise",
    title: "The Difference Between a Website That Looks Good and One That Gets Calls",
    description: "Many Boise service businesses have professional-looking sites that don't ring the phone. Here's what separates a site that looks good from one that actually generates calls.",
    date: "2027-01-12",
    dateDisplay: "January 12, 2027",
    readTime: "4 min read",
    category: "Web Design",
    coverImage: "/blog/website-gets-calls.webp",
    coverAlt: "Professional working on laptop representing a Boise website that generates phone calls",
  },
];
